import { overlay } from 'overlay-kit';
import NormalButton from '../../component/common/NormalButton';
import * as S from './DatabasePage.style';
import Overlay from '../../component/common/Overlay';
import DataUploadModal from './DataUploadModal';
import { useDatabaseContext } from '../store/databaseStore';
import DatabaseItem from '../components/DatabaseItem';
import { useMemo, useState } from 'react';
import { useClusterContext } from '../store/clusterStore';
import { Colors } from '../../style/colors';
import { useCriteriaContext } from '../store/criteriaStore';
import DatabaseSummary from '../components/DatabaseSummary';

const DatabasePage = () => {
  const { database, pairDataToAllClusterMap } = useDatabaseContext();
  const { getCriteriaById } = useCriteriaContext();
  const { findClusterById } = useClusterContext();
  const [selectedClusterIds, setSelectedClusterIds] = useState<string[]>([]);

  const presentedDatabase = useMemo(() => {
    if (selectedClusterIds.length === 0) return database;
    const result = database.filter((data) => {
      const dataToClusterItem = pairDataToAllClusterMap.get(data.id);
      return selectedClusterIds.every((cId) => dataToClusterItem?.clusters.includes(cId));
    });
    return result;
  }, [database, selectedClusterIds]);

  const openDatasetModal = () => {
    overlay.open(({ isOpen, close, unmount }) => {
      return (
        <Overlay isOpen={isOpen} close={close} unmount={unmount}>
          <DataUploadModal close={close} onComplete={unmount} />
        </Overlay>
      );
    });
  };

  const toggleSelectedClusterId = (id: string) => {
    if (selectedClusterIds.includes(id)) setSelectedClusterIds(selectedClusterIds.filter((i) => i !== id));
    else setSelectedClusterIds([...selectedClusterIds, id]);
  };

  return (
    <S.Container>
      <S.Header>
        <div className="text-container">
          <h3 className="title">Dataset</h3>
          <h3 className="desc">Upload your data that includes pairs of queries and outputs generated by an LLM</h3>
        </div>
      </S.Header>
      {database.length === 0 && (
        <S.Empty>
          Upload your dataset in JSON format.
          <NormalButton onClick={openDatasetModal}>+ Add Dataset</NormalButton>
        </S.Empty>
      )}
      {database.length !== 0 && selectedClusterIds.length > 0 && (
        <DatabaseSummary selectedClusterIds={selectedClusterIds} presentedDatabase={presentedDatabase} toggleId={toggleSelectedClusterId} />
      )}
      {database.length !== 0 &&
        presentedDatabase.map((data) => (
          <DatabaseItem key={`database-item-${data.id}`} data={data} selectedClusterIds={selectedClusterIds} toggleClusterId={toggleSelectedClusterId} />
        ))}
    </S.Container>
  );
};

export default DatabasePage;
